containers:
  api:
    image:
      repository: mojaloop/central-ledger
      tag: v10.4.2
      pullPolicy: Always

init:
  enabled: true
  mysql:
    name: wait-for-mysql
    repository: mysql
    tag: latest
    pullPolicy: Always
    command: "until mysql -h $db_host -P $db_port -u $db_user --password=$db_password  $db_database   -e 'select version()' ; do echo waiting for MySQL; sleep 2; done;"
  migration:
    enabled: true
    name: run-migration
    command: npm run migrate
    config:
      run_data_migration: true